name: RickAndMorty
options: 
  deploymentTarget: 
    iOS: 14.0

targets: 
  RickAndMorty:
    type: application
    platform: iOS
    deploymentTarget: 
      iOS: 14.0
    sources: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.rickandmorty
  RickAndMortyTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: 
      iOS: 14.0
    sources: Tests
    dependencies: 
      - target: RickAndMorty

schemes:
  RickAndMorty:
    build: 
      targets: 
        RickAndMorty: all
    test: 
      targets: 
        - name: RickAndMortyTests
          parallelizable: false
          randomExecutionOrder: true 
      gatherCoverageData: true